2025-08-25 11:06:42,321 INFO    MainThread:11304 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-25 11:06:42,321 INFO    MainThread:11304 [wandb_setup.py:_flush():80] Configure stats pid to 11304
2025-08-25 11:06:42,322 INFO    MainThread:11304 [wandb_setup.py:_flush():80] Loading settings from C:\Users\shado\.config\wandb\settings
2025-08-25 11:06:42,322 INFO    MainThread:11304 [wandb_setup.py:_flush():80] Loading settings from c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main\wandb\settings
2025-08-25 11:06:42,322 INFO    MainThread:11304 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-25 11:06:42,323 INFO    MainThread:11304 [wandb_init.py:setup_run_log_directory():703] Logging user logs to c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main\wandb\run-20250825_110642-8e731g3h\logs\debug.log
2025-08-25 11:06:42,325 INFO    MainThread:11304 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to c:\Users\shado\Documents\Master Thesis\INFORM_marine-main_new\INFORM_marine-main\wandb\run-20250825_110642-8e731g3h\logs\debug-internal.log
2025-08-25 11:06:42,325 INFO    MainThread:11304 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000021783102090>
2025-08-25 11:06:42,326 INFO    MainThread:11304 [wandb_init.py:init():830] calling init triggers
2025-08-25 11:06:42,326 INFO    MainThread:11304 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'learning_rate': 1e-05, 'epochs': 50, 'Weight_decay': 0.0001, '_wandb': {}}
2025-08-25 11:06:42,326 INFO    MainThread:11304 [wandb_init.py:init():871] starting backend
2025-08-25 11:06:42,786 INFO    MainThread:11304 [wandb_init.py:init():874] sending inform_init request
2025-08-25 11:06:43,505 INFO    MainThread:11304 [wandb_init.py:init():882] backend started and connected
2025-08-25 11:06:43,530 INFO    MainThread:11304 [wandb_run.py:_label_probe_notebook():1318] probe notebook
2025-08-25 11:06:43,546 INFO    MainThread:11304 [wandb_run.py:_label_probe_notebook():1328] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-08-25 11:06:43,546 INFO    MainThread:11304 [wandb_init.py:init():953] updated telemetry
2025-08-25 11:06:43,555 INFO    MainThread:11304 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-25 11:06:45,983 INFO    MainThread:11304 [wandb_init.py:init():1029] starting run threads in backend
2025-08-25 11:06:49,656 INFO    MainThread:11304 [wandb_run.py:_console_start():2494] atexit reg
2025-08-25 11:06:49,656 INFO    MainThread:11304 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-25 11:06:49,657 INFO    MainThread:11304 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-25 11:06:49,658 INFO    MainThread:11304 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-25 11:06:49,673 INFO    MainThread:11304 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-25 11:06:49,724 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:06:49,982 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:06:49,983 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:06:56,802 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:06:56,948 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:06:56,948 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:16:41,106 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:04,909 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:04,922 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:05,332 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:21,949 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:21,950 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:22,189 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:22,547 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:22,547 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:22,563 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:22,865 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:22,866 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:22,893 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:22,961 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:22,962 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:22,986 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:23,101 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:23,102 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:23,123 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:29:29,460 INFO    MainThread:11304 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-08-25 11:29:29,461 INFO    MainThread:11304 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-08-25 11:29:29,603 INFO    MainThread:11304 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-25 11:55:36,513 WARNING MsgRouterThr:11304 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\shado\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 200, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] En eksisterende tilkobling ble tvangslukket av den eksterne verten

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\shado\anaconda3\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shado\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 227, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shado\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 204, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\shado\anaconda3\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shado\anaconda3\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-08-25 11:55:36,703 INFO    MsgRouterThr:11304 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
